# Generated by Django 3.2.14 on 2022-07-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wantads', '0009_auto_20220711_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantadhit',
            name='created1',
            field=models.DateField(auto_now=True),
        ),
    ]
