# Generated by Django 3.2.14 on 2022-07-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wantads', '0010_wantadhit_created1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantadhit',
            name='created1',
            field=models.DateField(),
        ),
    ]
