# Generated by Django 3.2.14 on 2022-07-13 05:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wantads', '0011_alter_wantadhit_created1'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'want')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('user', 'want')},
        ),
        migrations.AlterUniqueTogether(
            name='viewed',
            unique_together={('user', 'want')},
        ),
    ]
