# Generated by Django 3.2.14 on 2022-07-13 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('1', 'فنی'), ('2', 'مالی'), ('3', 'پشتیبانی')], max_length=20)),
                ('status', models.CharField(choices=[('1', 'در انتظار پاسخ'), ('2', 'پاسخ داده شده'), ('3', 'بسته شده')], max_length=20)),
                ('closed_at', django_jalali.db.models.jDateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_who', models.CharField(choices=[('ادمین', 'ادمین'), ('کاربر', 'کاربر')], max_length=20)),
                ('body', models.TextField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
    ]
