# Generated by Django 3.2.14 on 2022-07-13 13:40

from django.db import migrations, models
import tickets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default=tickets.models.create_new_ref_number, max_length=124, unique=True),
        ),
    ]
