# Generated by Django 3.2.14 on 2022-07-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('در انتظار پاسخ', '1'), ('پاسخ داده شده', '2'), ('بسته شده', '3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('فنی', '1'), ('مالی', '2'), ('پشتیبانی', '3')], max_length=20),
        ),
    ]
